Repository gosh-sh/gosh, pull requests merged in 2022-11, with the labels that each got.

#166 Added support for git submodules
  git-remote-gosh/src/blockchain/create_branch.rs
  git-remote-gosh/src/blockchain/tree/save.rs
  git-remote-gosh/src/git_helper/fetch/mod.rs
  git-remote-gosh/src/git_helper/push/utilities/build_tree_diff.rs
  git-remote-gosh/src/git_helper/push/utilities/try_find_tree_leaf.rs
Labels: enhancement

#180 Bugfix/heads inconsist
  git-remote-gosh/src/git_helper/push/mod.rs
  tests/08-repo_with_canceled_diffs.test.sh
Labels: bug

#192 Added commits' chain calculation by first parent
  git-remote-gosh/src/git_helper/push/mod.rs
  git-remote-gosh/src/git_helper/push/push_diff.rs
Labels: bug

#197 [critical] CI: add protobuf-compiler
  git-remote-gosh/Dockerfile
Labels: bug, critical

#253 Bugfix/diff constructing
  git-remote-gosh/Cargo.toml
  git-remote-gosh/src/blockchain/contract.rs
  git-remote-gosh/src/blockchain/mod.rs
  git-remote-gosh/src/git_helper/mod.rs
  git-remote-gosh/src/git_helper/push/mod.rs
  git-remote-gosh/src/git_helper/push/push_diff.rs
  git-remote-gosh/src/git_helper/push/utilities/generate_blob_diff.rs
Labels: bug

#268 web: update prod envs
  react-gosh/src/gosh/1.0.0/adapter.ts
  react-gosh/src/hooks/repo.hooks.ts
  web/.env.docker.production
  web/.env.production
  web/src/pages/Commits/Commits.tsx
Labels: bug, critical

#275 Fixed processing msg with empty body
  git-remote-gosh/src/blockchain/call.rs
  git-remote-gosh/src/blockchain/snapshot/load/diffs/iterator.rs
  version.json
Labels: bug
